version: '3'
services:
  VulnerableApp-base:
    image: sasanlabs/owasp-vulnerableapp:unreleased
    # We assume the image is built locally using ./gradlew jibDockerBuild
    environment:
      - DB_ADMIN_USERNAME=admin
      - DB_ADMIN_PASSWORD=hacker
      - DB_APP_USERNAME=application
      - DB_APP_PASSWORD=hacker
    
  VulnerableApp-jsp:
    image: sasanlabs/owasp-vulnerableapp-jsp:latest

  VulnerableApp-php:
    image: sasanlabs/owasp-vulnerableapp-php:latest
  
  VulnerableApp-facade:
    depends_on:
      - VulnerableApp-base
      - VulnerableApp-jsp
      - VulnerableApp-php
    image: sasanlabs/owasp-vulnerableapp-facade:latest
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
